.TH MAILSYNC 1
.SH NAME
mailsync \- synchronisiert E-Mail-Konten, die mit
.B mw
eingerichtet wurden.
.SH ÜBERSICHT
.B mailsync
[
.I OPTIONEN
]... [
.I KONTEN
]
.SH BESCHREIBUNG
.B mailsync
synchronisiert die E-Mails aller mit
.B mw
eingerichteten Konten, oder wenn Kontonamen angegeben werden, synchronisiert es nur diese Konten.

.B mailsync
ist ein Wrapper für
.B mbsync
und
.B mpop,
aber indiziert auch automatisch neue E-Mails mit
.B notmuch,
gibt Benachrichtigungen aus, wenn neue E-Mails gefunden werden, und kann auch als Cronjob eingestellt werden, um E-Mails im Hintergrund still zu synchronisieren und zu indizieren.
.SH BEFEHLE
.TP
.B mailsync
alle E-Mail-Konten synchronisieren und Benutzer benachrichtigen, wenn es neue E-Mails gibt
.TP
.B mailsync konto@beispiel.de
nur das Konto
.B konto@beispiel.de
synchronisieren.
.SH KONFIGURATION
Während
.B mailsync
standardmäßig Benachrichtigungen beim Eintreffen neuer E-Mails gibt, kann dies durch Setzen der Variable
.I MAILSYNC_MUTE=1
deaktiviert werden.
.SH AUTOREN
Ursprünglich 2018 geschrieben von Luke Smith <luke@lukesmith.xyz>.
Deutsche Version und Anpassungen von Sergius.
.SH LIZENZ
GPLv3
.SH SIEHE AUCH
.BR mw (1),
.BR neomutt (1),
.BR neomuttrc (1)
.BR mbsync (1),
.BR mpop (1),
.BR msmtp (1),
.BR notmuch (1),
.BR abook (1)
