.TH MW 1 mutt-wizard
.SH NAME
mw \- mutt-wizard \- automatische Konfiguration von E-Mail-Konten für neomutt und mbsync
.SH ÜBERSICHT
.B mw
[
.I OPTIONEN
]
.SH BESCHREIBUNG
.B mw
nimmt ein Benutzer-E-Mail-Konto und richtet eine terminalbasierte E-Mail-Schnittstelle dafür mit
.B neomutt
ein. Dies kann Offline-E-Mail mit
.B mbsync
(aus dem isync-Paket) und Konfigurationen für
.B msmtp
zum Versenden von E-Mails beinhalten, sowie automatisch verschlüsselte und mit
.B pass
gespeicherte Passwörter.
.SH BEFEHLE
.TP
.B -a deine@email.com
eine E-Mail-Adresse hinzufügen
.TP
.B -l
alle von mutt-wizard konfigurierten E-Mail-Konten auflisten
.TP
.B -d
ein bereits konfiguriertes Konto auswählen und dessen Konfiguration entfernen
.TP
.B -D deine@email.com
ein konfiguriertes Konto ohne Bestätigung entfernen
.TP
.B -y deine@email.com
E-Mails für ein E-Mail-Konto herunterladen und hochladen
.TP
.B -Y
alle E-Mail-Konten synchronisieren
.TP
.B -t 15
einen Cronjob umschalten, der E-Mails alle 15 Minuten synchronisiert (oder jede andere Zahl unter 60)
.TP
.B -T
einen Cronjob umschalten ohne Angabe der Minuten zwischen Synchronisationen
.TP
.B -r
Konten-Kurztastennummern neu ordnen
.SH OPTIONEN ZUM HINZUFÜGEN VON KONTEN
Diese können auf der Befehlszeile angegeben werden, andernfalls werden Sie nach den notwendigen Informationen gefragt. mutt-wizard kennt die IMAP/SMTP-Server-Informationen für die meisten E-Mail-Anbieter, sodass deren Angabe normalerweise überflüssig ist.
.TP
.B -u billy
Konto-Login/Benutzername, falls erforderlich und abweichend von der E-Mail-Adresse.
.TP
.B -n Billy
Echter Name, der in E-Mails erscheint. Sollte in Anführungszeichen gesetzt werden, wenn er aus mehreren Wörtern besteht.
.TP
.B -m Zahl
Maximale Anzahl von Nachrichten festlegen, die offline gespeichert werden sollen.
.TP
.B -i
IMAP/POP-Serveradresse
.TP
.B -I
IMAP/POP-Server-Port (wird als 993 für IMAP und 995 für POP angenommen, falls nicht angegeben)
.TP
.B -s
SMTP-Serveradresse
.TP
.B -S
SMTP-Server-Port (wird als 465 angenommen, falls nicht angegeben)
.TP
.B -x
Kontopasswort. Sie werden interaktiv nach dem Passwort gefragt, wenn diese Option nicht angegeben wird.
.TP
.B -P
Pass-Präfix. Das Passwort wird mit pass unter <passpräfix><email> gespeichert
.SH WEITERE OPTIONEN
.TP
.B -f
Kontoerstellung erzwingen und Mailboxen erraten, ohne zu versuchen, sich mit dem Server zu verbinden. Andernfalls bleiben die konfigurierten Kontoeinstellungen nicht erhalten, wenn keine Verbindung hergestellt werden kann.
.TP
.B -o
Einstellungen für ein Konto erstellen, das nur online ohne E-Mail-Synchronisationsfähigkeiten verwendet werden soll. Ohne
.B -f
wird beim Setup dennoch versucht, eine Verbindung herzustellen, um Mailboxen zu erkennen.
.TP
.B -X
Beim Entfernen eines E-Mail-Profils mit entweder
.I -d
oder
.I -D
auch die lokalen E-Mails löschen (löscht die E-Mails auf dem Server nicht).
.TP
.B -p
POP-Protokoll statt IMAP verwenden. Erfordert
.I mpop
zum Herunterladen von E-Mails nach der Konfiguration. Server-Details können weiterhin mit den Optionen
.I -i
und
.I -I
angegeben werden, als wäre es IMAP.
.SH DETAILS
.TP
.B mailsync
mutt-wizard ruft ein Skript namens
.I mailsync
auf, um E-Mails zu synchronisieren. Dieses Skript indiziert zusätzlich neue E-Mails mit notmuch und gibt Ihnen eine Benachrichtigung, wenn neue E-Mails eingetroffen sind. Wenn Sie die zusätzlichen Funktionen umgehen möchten, können Sie jederzeit einfach
.I mbsync -a
ausführen, um Ihre E-Mails direkt zu synchronisieren.
.TP
.B Mail-Speicherort
Wenn der Benutzer sich entscheidet, Offline-E-Mails mit
.B mbsync
zu speichern, werden sie in
.I ~/.local/share/mail/
aufbewahrt.
.B notmuch
kann verwendet werden, um diese E-Mails zu indizieren und zu durchsuchen, indem dieses Verzeichnis beim ersten Ausführen von
.B notmuch setup
angegeben wird. Wenn Sie notmuch noch nicht eingerichtet haben, wird mutt-wizard es beim ersten Hinzufügen eines Kontos automatisch im Hintergrund einrichten.
.TP
.B muttrc-Dateien
mutt-wizard erstellt für jedes erstellte Konto eine muttrc-Datei mit kontospezifischen Details. Diese erscheinen in
.I ~/.config/mutt/accounts/
und können vom Benutzer bei Bedarf bearbeitet werden. Beachten Sie, dass mutt-wizard diese Dateien auch einbindet und die Tastenbelegungen zum Wechseln zwischen ihnen erstellt, die in Ihrer Standard-
.I ~/.config/mutt/muttrc
-Datei erscheinen.
.TP
.B E-Mail-Löschung
Die Löschaktion von mutt-wizard löscht Konfigurationsdateien und
.I nicht
heruntergeladene E-Mails aus Sicherheits- (und Zeit-)Gründen. Wenn Sie heruntergeladene E-Mails löschen möchten, tun Sie dies manuell, indem Sie sie aus dem obigen Verzeichnis entfernen.
.TP
.B Standardeinstellungen
mutt-wizard hat viele Standardeinstellungen, die sich darauf konzentrieren, es ästhetisch ansprechend zu machen und mehr vim-ähnliche Tastenbelegungen bereitzustellen. Diese befinden sich in
.I /usr/local/share/mutt-wizard/mutt-wizard.muttrc
und die Standard-Mailcap-Datei befindet sich in
.I /usr/local/share/mutt-wizard/mailcap.
Jede dieser Einstellungen kann in
.I ~/.config/mutt/muttrc
überschrieben werden, aber beachten Sie, dass Ihre überschreibenden Tastenbelegungen nach dem Einbinden der
.I mutt-wizard.muttrc
-Datei erscheinen sollten.
.TP
.B Erkennung von Servereinstellungen
mutt-wizard hat ein Repository von E-Mail-Diensten und deren Serverinformationen in
.I /usr/local/share/mutt-wizard/domains.csv,
das zur automatischen Konfiguration von E-Mail-Einstellungen verwendet wird. Wenn Ihr E-Mail-Anbieter dort nicht gefunden wird, werden Sie aufgefordert, die IMAP- und SMTP-Server-Informationen Ihres E-Mail-Dienstes einzugeben, die normalerweise durch Online-Suche gefunden werden können.

Wenn Sie helfen möchten, mutt-wizard für andere weiterzuentwickeln, sind Sie eingeladen, diese Dienstinformationen zu
.I domains.csv
auf der Codeberg-Seite von mutt-wizard <https://codeberg.org/Sergius/mutt-wizzard-de> oder der Github-Seite des Originals <https://github.com/lukesmithxyz/mutt-wizard> hinzuzufügen.
.TP
.B Gmail-Konten
Google verlangt, dass Sie "weniger sichere" (Drittanbieter-)Anwendungen zulassen oder die Zwei-Faktor-Authentifizierung entfernen, um auf ihre IMAP-Server zuzugreifen und Ihre E-Mails herunterzuladen. Wenn Sie Gmail verwenden, stellen Sie sicher, dass Sie dies erledigen, bevor Sie mutt-wizard ausführen. Erstellen Sie ein App-Passwort unter <https://myaccount.google.com/apppasswords>.
.TP
.B Unternehmens- und Universitätskonten
Viele Universitäten und Unternehmen hosten die E-Mail ihrer Domain möglicherweise über Google oder einen anderen Dienst. Dies erfordert oft ein spezielles IMAP/SMTP-spezifisches Passwort, das Sie generieren und verwenden müssen. Auch hier kann mutt-wizard diese Systeme handhaben, aber erst nachdem sie eingerichtet wurden.
.TP
.B Passwort-Entschlüsselung
mutt-wizard verwendet
.I pass
und daher
.I gpg
zum Entschlüsseln Ihrer Passwörter. Vorausgesetzt, Ihr GPG-Schlüssel hat ein Passwort, bedeutet dies möglicherweise, dass Sie beim ersten Synchronisieren oder Senden von E-Mails in einer Sitzung nach Ihrem GPG-Passwort gefragt werden. Sobald Ihr Passwort zwischengespeichert ist, kann es auch später ablaufen.

Aus diesem Grund empfehle ich das Programm
.I pam-gnupg
<https://github.com/cruegge/pam-gnupg> dringend, das Ihr GPG-Passwort beim Login automatisch entsperrt und aktiv hält und Ihnen so mit mutt-wizard sicheren Zugriff auf alle Ihre E-Mail-Konten auf Ihrem System gibt, ohne jemals ein Passwort eingeben zu müssen.

Wenn Sie dieses Programm nicht verwenden möchten, können Sie auch die Cache-Zeit eines eingegebenen GPG-Passworts mit den Variablen
.I default-cache-ttl
und
.I max-cache-ttl
in Ihrer
.I gpg-agent.conf
erhöhen.
.SH MUTT-WIZARDS NEOMUTT-KONFIGURATION
Hier ist eine Liste nicht nur der speziellen Standardeinstellungen von mutt-wizard, sondern auch dessen, was Sie brauchen, um das Beste aus mit mutt-wizard konfigurierten E-Mail-Konten herauszuholen.
.TP
.B Farbe
Die Standardeinstellungen von mutt-wizard fügen Farbe zu Nachrichten im Index hinzu und färben E-Mail-Details ein, um sie leichter erkennbar zu machen. Neue E-Mails werden nicht nur durch das typische N markiert, sondern auch fett dargestellt.
.TP
.B Bewegung mit h/j/k/l
Verwenden Sie Vim-Tasten, um in E-Mails nach unten
.I j
oder nach oben
.I k
zu navigieren, während
.I l
E-Mails öffnet, dann die Anhangansicht, dann einen Anhang, während
.I h
das Gegenteil ist. Während eine E-Mail geöffnet ist, gehen Sie zur nächsten oder vorherigen E-Mail mit
.I J
und
.I K.
Im E-Mail-Index gehen
.I d
und
.I u
eine halbe Seite nach unten und oben und
.I gg
und
.I G
gehen ganz nach oben und ganz nach unten.
.TP
.B E-Mails durchsuchen
Wenn Sie
.B notmuch
mit Ihrem richtigen E-Mail-Verzeichnis konfiguriert haben (siehe oben), können Sie
.I Strg-f
ausführen, um nach E-Mails zu suchen, die eine bestimmte Sequenz enthalten. Auch ohne notmuch begrenzt
.I L
E-Mails und zeigt nur diejenigen mit der angegebenen Sequenz im Betreff, während
.I A
alle E-Mails zeigt (dasselbe wie Begrenzung auf "all").
.TP
.B E-Mails löschen
.I D
löscht E-Mails, während
.I U
sie wiederherstellt (geben Sie die E-Mail-Nummer ein, um zu gelöschten E-Mails zu gelangen). Beachten Sie, dass
.I S
Ihre Mailbox speichert und die Löschung endgültig macht. Wenn Sie eine
.I Trash
-Box haben, werden gelöschte E-Mails dorthin verschoben. Wenn Sie möchten, dass dies übersprungen wird und sie einfach gelöscht werden, kommentieren Sie die Zeile
.I set trash
in der muttrc dieses Kontos aus oder entfernen Sie sie.
.TP
.B E-Mails versenden
.I m
erstellt eine neue E-Mail-Nachricht;
.I r
antwortet auf die ausgewählte Nachricht;
.I R
antwortet allen auf die ausgewählte Nachricht und
.I f
leitet die ausgewählte Nachricht weiter.
.TP
.B E-Mail-Verfassungsbildschirm
Sobald Sie eine E-Mail geschrieben und den Puffer gespeichert haben, werden Sie zum Verfassungsbildschirm gebracht. Drücken Sie
.I a,
um Anhänge hinzuzufügen, verwenden Sie
.I s/t/c/b/d,
um Betreff/An/CC/BCC/Beschreibung zu ändern. Drücken Sie
.I S,
um die Signatur/Verschlüsselung zu ändern. Drücken Sie
.I y,
um die E-Mail zu senden.
.TP
.B E-Mail-Adressen mit abook speichern und automatisch vervollständigen
Installieren Sie die optionale Abhängigkeit abook und Sie können die E-Mail-Adresse des Absenders mit
.I a
speichern. Sobald dies geschehen ist, können Sie beim Tippen in einer E-Mail-/Kontaktabfrage
.I Tab
drücken, um Kontakte zu finden, die Ihrer Eingabe entsprechen. Obwohl abook oft mit mutt verwendet wird, ist es auch an sich ein nützliches Programm.
.TP
.B Wechseln und Verschieben von E-Mails zwischen Mailboxen
Die
.I g
-Taste kann mit mehreren anderen Tasten kombiniert werden, um automatisch zu einer anderen Mailbox zu wechseln: gi: Posteingang; gs: Gesendet; gd: Entwürfe; ga: Archiv; gS: Spam; gj: Junk; gt: Papierkorb. Diese Tastenbelegungen sind nur für Konten vorhanden, die die betreffenden Boxen haben. Anstelle von
.I g
können Sie auch
.I C
drücken, um E-Mails zu kopieren, oder
.I M,
um E-Mails in dieselben Boxen zu verschieben.
.TP
.B Zwischen Konten wechseln
mutt-wizard kann bis zu neun Konten konfigurieren, die jeweils mit der niedrigsten verfügbaren Nummer nummeriert werden, wenn sie konfiguriert werden. Drücken Sie
.I i
gefolgt von der Nummer eines Kontos, um zu diesem Konto zu wechseln: i2, i5, usw.
.I Strg-b,
um ein Menü zu öffnen und eine URL auszuwählen, die Sie in Ihrem Browser öffnen möchten.
.TP
.B Seitenleiste
mutt-wizard aktiviert standardmäßig die Seitenleiste, die die Boxen Ihres Kontos mit E-Mail-Anzahlen anzeigt.
.I B
schaltet die Seitenleiste um. Bewegen Sie sich darin auf und ab mit
.I Strg-k/j.
Öffnen Sie eine Box mit
.I Strg-o.
.TP
.B Weitere Informationen
Denken Sie daran, dass Sie jederzeit
.I ?
in neomutt drücken können, um eine Liste aller Tastenbelegungen und Funktionen zu erhalten. Diese Liste kann auch für verschiedene Kontextmenüs variieren.
.SH AUTOREN
Ursprünglich 2018 geschrieben von Luke Smith <luke@lukesmith.xyz>.
Deutsche Version und Anpassungen von Sergius.
.SH LIZENZ
GPLv3
.SH SIEHE AUCH
.BR mailsync (1),
.BR neomutt (1),
.BR neomuttrc (1)
.BR mbsync (1),
.BR mpop (1),
.BR msmtp (1),
.BR notmuch (1),
.BR abook (1)
